name: Development

on:
   push:
      branches:
        - '**'
   workflow_call:
   workflow_dispatch:

jobs:
   test:
      name: Lint and Test
      uses: uicpharm/workflows/.github/workflows/lint-and-test.yml@v1
