name: Release Moodle Plugin

on:
   push:
      tags:
         - '*'

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: Check version matches tag name
           run: |
               version=$(grep -Eo '^\s*\$plugin->version\s*=\s*[0-9]+' src/version.php | grep -Eo '[0-9]+')
               tag=${GITHUB_REF#refs/tags/}
               if [[ $version != $tag ]]; then
                  echo "❌ Version mismatch: Tag is $tag but version is $version."
                  exit 1
               else
                  echo "✅ Version match: $tag"
               fi
         - uses: actions/setup-node@v4
           with:
               node-version-file: ".nvmrc"
               cache: "npm"
         - run: npm ci
         - run: npm run build:plugin
         - name: Upload Release Asset
           uses: softprops/action-gh-release@v2
           with:
               files: "dist/package/*.zip"
           env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
